# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import coSim_pb2 as coSim__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coSim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoSimStub(object):
    """
    This file defines the protocol for the co-simulation service.
    It includes service definitions, message types, and RPC methods for managing a federate.
    Any federate(simulator/stand alone functional model) that wants to be part of the co-simulation must implement an interface using gRPC containing these methods/services.
    The services allow starting the simulation, executing/advancing time steps, managing hosts, and exchanging and 
    commanding attributes between different simulators or functional models in the co-simulation.
    The messages are used to exchange data between the federates and the co-simulation service.
    The messages are defined in a way that allows for extensibility, so you can add your own attributes or types as needed.


    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/coSim.CoSim/Start',
                request_serializer=coSim__pb2.Config.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ExecuteOneTimeStep = channel.unary_unary(
                '/coSim.CoSim/ExecuteOneTimeStep',
                request_serializer=coSim__pb2.StepRequest.SerializeToString,
                response_deserializer=coSim__pb2.StepReply.FromString,
                _registered_method=True)
        self.Finish = channel.unary_unary(
                '/coSim.CoSim/Finish',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetManagedHosts = channel.unary_unary(
                '/coSim.CoSim/GetManagedHosts',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coSim__pb2.VehicleList.FromString,
                _registered_method=True)
        self.InsertHost = channel.unary_unary(
                '/coSim.CoSim/InsertHost',
                request_serializer=coSim__pb2.HostId.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteHost = channel.unary_unary(
                '/coSim.CoSim/DeleteHost',
                request_serializer=coSim__pb2.HostId.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetAttribute = channel.unary_unary(
                '/coSim.CoSim/SetAttribute',
                request_serializer=coSim__pb2.Request.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAttribute = channel.unary_unary(
                '/coSim.CoSim/GetAttribute',
                request_serializer=coSim__pb2.Request.SerializeToString,
                response_deserializer=coSim__pb2.Request.FromString,
                _registered_method=True)
        self.QueryRequest = channel.unary_unary(
                '/coSim.CoSim/QueryRequest',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coSim__pb2.Requests.FromString,
                _registered_method=True)


class CoSimServicer(object):
    """
    This file defines the protocol for the co-simulation service.
    It includes service definitions, message types, and RPC methods for managing a federate.
    Any federate(simulator/stand alone functional model) that wants to be part of the co-simulation must implement an interface using gRPC containing these methods/services.
    The services allow starting the simulation, executing/advancing time steps, managing hosts, and exchanging and 
    commanding attributes between different simulators or functional models in the co-simulation.
    The messages are used to exchange data between the federates and the co-simulation service.
    The messages are defined in a way that allows for extensibility, so you can add your own attributes or types as needed.


    """

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteOneTimeStep(self, request, context):
        """Start:  This RPC should allow your application to instantiate. If you require a config file or some pamaraters to 
        instantiate we can pass it as Config message.
        Calling this RPC multiple times should be possible, by createing new instance at each call.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finish(self, request, context):
        """ExecuteOneTimeStep: This RPC should allow your application to advance one step of simulation time. This is the amount of time the simulation time should be advanced for your application and then wait until the next step is requested.
        The time for each step is defined through the Start(Config) RPC. Also it should be possible to dynamically change it at runtime
        by passing a new value as part of the StepRequest message. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManagedHosts(self, request, context):
        """
        Finish: This RPC should allow your application to finish the simulation. And clean up any resources it has allocated.
        It should be called at the end of the simulation. Later on it should extended to forward result files as well.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertHost(self, request, context):
        """
        GetManagedHosts: This RPC should allow your application to get the list of managed hosts(UE), along with their current state, i.e. 
        their position, speed, angle, etc. This is the list of hosts that your application is responsible for managing.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHost(self, request, context):
        """InsertHost: This RPC should allow your application to insert a new host into the co-simulation. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttribute(self, request, context):
        """DeleteHost: This RPC should allow your application to delete a host it is currently maintaining
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttribute(self, request, context):
        """SetAttribute: This RPC should allow your application to set an attribute for a host or a group of hosts.
        e.g. speed, route, shape, boundarys, etc.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRequest(self, request, context):
        """GetAttribute: This RPC should allow your application to get an attribute for a host or a group of hosts or simulation
        QueryRequest: This RPC should allow your application to query the requests that are currently pending after advancing each simulation step.
        It could be anything that you want from other simulators that are coupled. This RPC will be called at the very beginning after starting your *federate and also after each ExecuteOneTimeStep rpc call. 
        This is useful to interact with other simulator in the co-simulation, synchronously.
        This is how you interact with other simulators in the co-simulation, as a form and request and response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoSimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=coSim__pb2.Config.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExecuteOneTimeStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOneTimeStep,
                    request_deserializer=coSim__pb2.StepRequest.FromString,
                    response_serializer=coSim__pb2.StepReply.SerializeToString,
            ),
            'Finish': grpc.unary_unary_rpc_method_handler(
                    servicer.Finish,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetManagedHosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManagedHosts,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coSim__pb2.VehicleList.SerializeToString,
            ),
            'InsertHost': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertHost,
                    request_deserializer=coSim__pb2.HostId.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHost,
                    request_deserializer=coSim__pb2.HostId.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttribute,
                    request_deserializer=coSim__pb2.Request.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttribute,
                    request_deserializer=coSim__pb2.Request.FromString,
                    response_serializer=coSim__pb2.Request.SerializeToString,
            ),
            'QueryRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRequest,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coSim__pb2.Requests.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coSim.CoSim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coSim.CoSim', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoSim(object):
    """
    This file defines the protocol for the co-simulation service.
    It includes service definitions, message types, and RPC methods for managing a federate.
    Any federate(simulator/stand alone functional model) that wants to be part of the co-simulation must implement an interface using gRPC containing these methods/services.
    The services allow starting the simulation, executing/advancing time steps, managing hosts, and exchanging and 
    commanding attributes between different simulators or functional models in the co-simulation.
    The messages are used to exchange data between the federates and the co-simulation service.
    The messages are defined in a way that allows for extensibility, so you can add your own attributes or types as needed.


    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/Start',
            coSim__pb2.Config.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteOneTimeStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/ExecuteOneTimeStep',
            coSim__pb2.StepRequest.SerializeToString,
            coSim__pb2.StepReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/Finish',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManagedHosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/GetManagedHosts',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coSim__pb2.VehicleList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/InsertHost',
            coSim__pb2.HostId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/DeleteHost',
            coSim__pb2.HostId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/SetAttribute',
            coSim__pb2.Request.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/GetAttribute',
            coSim__pb2.Request.SerializeToString,
            coSim__pb2.Request.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coSim.CoSim/QueryRequest',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coSim__pb2.Requests.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
